name: Run Frontend Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd react-hooks-frontend
          npm install

      - name: List files
        run: |
          cd react-hooks-frontend
          ls

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./react-hooks-frontend
          file: ./react-hooks-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-reactapp:latest

      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --name frontend-reactapp ${{ secrets.DOCKERHUB_USERNAME }}/frontend-reactapp:latest

