name: Spring Boot Application CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean install
        working-directory: springboot-backend

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t springboot-backend:latest .

      # Step 5: Push Docker image to Docker Hub (or another container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag springboot-backend:latest sruthivg22012002/springboot-backend:latest
          docker push sruthivg22012002/springboot-backend:latest

      # Step 6: Deploy to a server (Optional, adjust based on your setup)
      - name: Deploy Application
        run: |
          ssh user@sruthi "docker pull sruthivg22012002/springboot-backend:latest && \
          docker stop springboot-backend || true && \
          docker rm springboot-backend || true && \
          docker run -d -p 8080:8080 --name springboot-backend sruthivg22012002/springboot-backend:latest"

