name: Spring Boot Application CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Start MySQL container
      - name: Start MySQL
        run: |
          docker run -d --name mysql-container \
            -e MYSQL_ROOT_PASSWORD=0612 \
            -e MYSQL_DATABASE=employees \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=0612 \
            -p 3306:3306 mysql:8.0
          # Wait for MySQL to initialize
          for i in {1..30}; do
            docker exec mysql-container mysqladmin ping -h "127.0.0.1" --password=0612 && break || sleep 2;
          done

      # Step 4: Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean
        working-directory: ./springboot-backend

      - name: Build with Maven
        run: mvn install -DskipTests
        working-directory: ./springboot-backend

      # Step 5: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t backend-springboot:latest .
        working-directory: ./springboot-backend

      # Step 6: Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag backend-springboot:latest sruthivg22012002/backend-springboot:latest
          docker push sruthivg22012002/backend-springboot:latest

      # Step 7: Deploy to a server
      - name: Deploy Application
        run: |
          ssh user@sruthi "docker pull sruthivg22012002/backend-springboot:latest && \
          docker stop backend-springboot || true && \
          docker rm backend-springboot || true && \
          docker run -d -p 8080:8080 --name backend-springboot sruthivg22012002/backend-springboot:latest"

